
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-weave-works-v1alpha1-profilesubscription
  failurePolicy: Fail
  name: mprofilesubscription.kb.io
  rules:
  - apiGroups:
    - weave.works
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - profilesubscriptions
  sideEffects: None
